//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontUserApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string CarNo { get; set; }
        public string CarImage { get; set; }
        public string CarName { get; set; }
        public string CarModel { get; set; }
        public string CarYear { get; set; }
        public string CarType { get; set; }
        public Nullable<int> NoOfOwners { get; set; }
        public Nullable<bool> CarVerified { get; set; }
        public Nullable<bool> CarSold { get; set; }
        public Nullable<int> CarUid { get; set; }
        public string City { get; set; }
    }
}
