//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSoldHistory
    {
        public int CarNo { get; set; }
        public string CarName { get; set; }
        public string SellerName { get; set; }
        public string BuyerName { get; set; }
    }
}
